FROM hybridgroup/gocv:latest as build

WORKDIR /build

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app

FROM gocv/opencv:4.5.3

COPY --from=build /go/bin/app /go/bin/

ENTRYPOINT ["/go/bin/app"]